[tool.poetry]
name = "calendar-sync-helper"
version = "0.1.0"
description = ""
authors = ["Marius Shekow"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "0.115.2"}
validators = "0.34.0"
pytest = "8.3.3"
