services:
  - type: web
    name: ng-outlook-google-calendar-sync
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        # renovate: datasource=docker name=python
        value: "3.12.9"
      - key: POETRY_VERSION
        # renovate: datasource=pypi name=poetry
        value: "2.1.2"
