name: CI

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - name: Run Tests
        run: |
          pip install -r requirements-poetry.txt
          python3 -m venv .venv
          source .venv/bin/activate
          poetry install --with test
          pytest tests
        env:
          GITHUB_INTEGRATION_TEST_PAT: ${{ secrets.GH_INTEGRATION_TEST_PAT }}
          GITHUB_INTEGRATION_TEST_OWNER_REPO_BRANCH: "MShekow/ng-outlook-google-calendar-sync/github-integration-test"
  docker-smoke-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build Docker image and run smoke test
        run: |
          docker compose up -d
          sleep 5
          curl http://localhost:8000
          docker compose down
